version: '3.5'

services:
    atm-clientes-api:
        container_name: atm-${PROJECT_NAME}-latest
        build:
            args:
                - BUILD_CONFIG=Release
                - HTTP_PORT=80
                - HTTPS_PORT=443
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 5676:80
            - 5677:443